query GetCurrentApps {
  getCurrentApps {
    app_id
    name
    description
    type
    languages
    pictures
    access
    push
    creatorId
    creator {
      name
      user_id
      email
      nickName
      phone
      role
      avatar
    }
  }
}

mutation CreateApp(
  $name: String!
  $type: AppTypeEnum!
  $languages: [LanguageTypeEnum!]!
  $pictures: [String!]!
  $description: String
) {
  createApp(
    name: $name
    type: $type
    languages: $languages
    pictures: $pictures
    description: $description
  )
}
