# 用户邮箱&密码注册
mutation register($email: String!, $password: String!) {
  register(email: $email, password: $password)
}

# 邮箱&密码登录
mutation login($email: String!, $password: String!) {
  login(email: $email, password: $password)
}

# 编辑用户信息
mutation updateUserInfo(
  $name: String
  $phone: String
  $nickName: String
  $role: UserRoleEnum
  $avatar: String
) {
  updateUserInfo(
    name: $name
    phone: $phone
    nickName: $nickName
    role: $role
    avatar: $avatar
  )
}

# 获取当前登录用户的基本信息
query getCurrentUser {
  getCurrentUser {
    name
    user_id
    email
    nickName
    phone
    role
    avatar
    verifyType
  }
}

# 发送验证邮件
mutation sendVerifyEmail {
  sendVerifyEmail
}

# 邮箱验证
mutation verifyEmail {
  verifyEmail
}

# 发送重设密码链接
mutation sendResetPasswordEmail($email: String!) {
  sendResetPasswordEmail(email: $email)
}

mutation resetPassword($password: String!) {
  resetPassword(password: $password)
}
