# 获取所有公共词条（分页）
query pageAllPublicEntries($pageSize: Int!, $pageNo: Int!, $key: String, $mainLangText: String, $startTime: Float, $endTime: Float) {
  pageAllPublicEntries(
    pageSize: $pageSize
    pageNo: $pageNo
    key: $key
    mainLangText: $mainLangText
    startTime: $startTime
    endTime: $endTime
  ) {
    total
    pageSize
    current
    records {
      entry_id
      key
      creatorId
      createdAt
      updatedAt
      archive
      deleted
      mainLangText
      mainLang
      modifyRecords {
        record_id
        createdAt
        entryEntry_id
        prevLangs
        currLangs
        prevKey
        currKey
        creator
        creatorInfo {
          name
          user_id
          email
          nickName
          phone
          role
          avatar
          verifyType
        }
      }
      langs
    }
  }
}

# 创建词条，如果不穿入appId，则创建为公共词条
mutation createEntry($appId: Int, $langs: JSONObject!, $key: String!) {
  createEntry(appId: $appId, langs: $langs, key: $key)
}

mutation updateEntry($entryId: Int!, $appId: Int, $langs: JSONObject, $key: String) {
  updateEntry(entryId: $entryId, appId: $appId, langs: $langs, key: $key)
}

# 获取应用所有词条（分页）
query pageAppEntries($pageSize: Int!, $pageNo: Int!, $appId: Int!, $startTime: Float, $endTime: Float, $mainLangText: String, $latest: Boolean, $key: String, $archive: Boolean) {
  pageAppEntries(
    pageSize: $pageSize
    pageNo: $pageNo
    appId: $appId
    startTime: $startTime
    endTime: $endTime
    mainLangText: $mainLangText
    latest: $latest
    key: $key
    archive: $archive
  ) {
    total
    pageSize
    current
    records {
      entry_id
      key
      creatorId
      createdAt
      updatedAt
      archive
      deleted
      mainLangText
      mainLang
      modifyRecords {
        record_id
        createdAt
        entryEntry_id
        prevLangs
        currLangs
        prevKey
        currKey
        creator
        creatorInfo {
          name
          user_id
          email
          nickName
          phone
          role
          avatar
          verifyType
        }
      }
      langs
    }
  }
}

# 归档词条或者删除词条（仅针对非公共词条）
mutation changeEntryAccessStatus($appId: Int!, $entryId: Int!, $archive: Boolean, $deleted: Boolean) {
  changeEntryAccessStatus(
    appId: $appId
    entryId: $entryId
    archive: $archive
    deleted: $deleted
  )
}

# 删除（批量）应用词条
mutation deleteEntries($appId: Int!, $entryIds: [Int!]!) {
  deleteEntries(appId: $appId, entryIds: $entryIds)
}

# 词条key应用内唯一校验
query validEntryKey($appId: Int, $entryId: Int, $key: String) {
  validEntryKey(appId: $appId, entryId: $entryId, key: $key)
}

# 通过excel上传词条
mutation uploadEntriesXlsx($appId: Int!, $fileUrl: String!) {
  uploadEntriesXlsx(appId: $appId, fileUrl: $fileUrl)
}

# 公共词条、私有词条相互转换
mutation transformEntry($entryId: Int!, $targetAppId: Int) {
  transformEntry(entryId: $entryId, targetAppId: $targetAppId)
}

# 通过中文查询公共词条
query queryPublicEntryByMainText($mainText: String!) {
  queryPublicEntryByMainText(mainText: $mainText) {
    entry_id
    key
    creatorId
    createdAt
    updatedAt
    archive
    deleted
    mainLangText
    mainLang
    langs
  }
}