query PageAllPublicEntries($pageSize: Int!, $pageNo: Int!) {
  pageAllPublicEntries(pageSize: $pageSize, pageNo: $pageNo) {
    entry_id
    key
    createdAt
    updatedAt
    public
    archive
    deleted
    modifyRecords {
      record_id
      createdAt
      entryEntry_id
      prevLangs
    }
    langs
  }
}
