query PageAllPublicEntries($pageSize: Int!, $pageNo: Int!) {
  pageAllPublicEntries(pageSize: $pageSize, pageNo: $pageNo) {
    total
    pageSize
    current
    records {
      entry_id
      key
      createdAt
      updatedAt
      public
      archive
      deleted
      mainLangText
      mainLang
      modifyRecords {
        record_id
        createdAt
        entryEntry_id
        prevLangs
        currLangs
        prevKey
        currKey
        creatorInfo {
          name
          user_id
          email
          nickName
          phone
          avatar
        }
      }
      langs
    }
  }
}

mutation CreateEntry($appId: Int, $langs: JSONObject, $key: String) {
  createEntry(appId: $appId, langs: $langs, key: $key)
}

mutation UpdateEntry($entryId: Int!, $langs: JSONObject, $key: String) {
  updateEntry(entryId: $entryId, langs: $langs, key: $key)
}

query PageAppEntries(
  $pageSize: Int!
  $pageNo: Int!
  $appId: Int!
  $startTime: Float
  $endTime: Float
  $mainLangText: String
  $latest: Boolean
  $key: String
) {
  pageAppEntries(
    pageSize: $pageSize
    pageNo: $pageNo
    appId: $appId
    startTime: $startTime
    endTime: $endTime
    mainLangText: $mainLangText
    latest: $latest
    key: $key
  ) {
    total
    pageSize
    records {
      entry_id
      key
      createdAt
      updatedAt
      public
      archive
      deleted
      mainLangText
      mainLang
      modifyRecords {
        record_id
        createdAt
        entryEntry_id
        prevLangs
        currLangs
        prevKey
        currKey
        creatorInfo {
          name
          user_id
          email
          nickName
          phone
          role
          avatar
        }
      }
      langs
    }
  }
}

mutation ChangeEntryAccessStatus(
  $appId: Int!
  $entryId: Int!
  $archive: Boolean
  $deleted: Boolean
) {
  changeEntryAccessStatus(
    appId: $appId
    entryId: $entryId
    archive: $archive
    deleted: $deleted
  )
}
