# 反馈(新增/修改描述)
mutation feedback(
  $result: Boolean!
  $userId: Int
  $message: String
  $feedbackId: Int
) {
  feedback(
    result: $result
    userId: $userId
    message: $message
    feedbackId: $feedbackId
  )
}
